# relative to starting position of the vehicle (m)
# float64 x
# float64 y
# float64 z
geometry_msgs/Point position

# (m/s)
# float64 x
# float64 y
# float64 z
geometry_msgs/Vector3 velocity

# (m/s/s)
# float64 x
# float64 y
# float64 z
geometry_msgs/Vector3 acceleration

# (positive is anti-clockwise, negative is clockwise)
float64 angle

# (positive is anti-clockwise, negative is clockwise)
float64 anglular_velocity